### ISSUE TITLE
Template Import Failed - Invalid parameter 

### ISSUE THREAD

**Issue by captainx720** [patricegautier/unifiZabbix#4]
Receiving following error when importing zabbix template.  Running Zabbix 5.2.2.

Invalid parameter "/interfaceid": cannot be empty.

**Comment by patricegautier** [comment]
any more info in /var/log/zabbix_server.log?

**Comment by tcatut** [comment]
I had a similar error when trying to import the most recent template update into Zabbix 5.0.  I did a little conversion on the params fields to make them 5.0 compatible, but then got this same interfaceid error.

Turns out, you need to remove any old version of the templates as he indicates in the README.  I had the prior version imported, which didn't work right anyway.  Once I removed the old version of the templates, and re-imported the new version, the interfaceid message went away.

I just checked on one of my Unifi AP units and latest data is refreshing all the data points just fine.

**Comment by patricegautier** [comment]
Ok good to know – I will add that part to the Readme.

**Comment by patricegautier** [comment]
@captainx720 can you confirm this fixes your issue?

**Comment by captainx720** [comment]
1Yes, That was the problem.  Thanks!
