### ISSUE TITLE
Number of clients for APs?

### ISSUE THREAD

**Issue by hellojoe88** [patricegautier/unifiZabbix#75]
Hello,

I greatly appreciate this template and I am happy to finally have this to monitor our APs. I am currently struggeling with wifi throughput so this will greatly help me identify potential problems. 

It would be amazing to have the number of clients to know if this might be a potential issue (e.g. too many clients causing to much traffic):

![grafik](https://user-images.githubusercontent.com/1126804/209796114-4c7c952c-3f8c-466a-b0da-4805d45d2890.png)

In the controller I can only look up the current number of clients, not the history of it, which would be simply amazing to have.

**Comment by patricegautier** [comment]
Try this latest commit on for size..

**Comment by hellojoe88** [comment]
Thank you so much, this is much appreciated! Especially since you have done it so fast.

I tested it and got this error:

`Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b.Usage /usr/lib/zabbix/exte...
1. Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b.Usage /usr/lib/zabbix/exte...
2. Failed: cannot extract value from json by path "$.sys_stats.mem_total": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b
Usage /usr/lib/zabbix/externalscripts/mca-dump-short.sh -i privateKeyPath -p <passwordFilePath> -u user -v -d target`

**Comment by patricegautier** [comment]
Did you install the updated mca-dump-short in the right spot(s)?Sent from my iPadOn Jan 10, 2023, at 9:41 AM, Johannes Pfeifer ***@***.***> wrote:﻿
Thank you so much, this is much appreciated! Especially since you have done it so fast.
I tested it and got this error:
`Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b.Usage /usr/lib/zabbix/exte...

Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b.Usage /usr/lib/zabbix/exte...
Failed: cannot extract value from json by path "$.sys_stats.mem_total": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b
Usage /usr/lib/zabbix/externalscripts/mca-dump-short.sh -i privateKeyPath -p  -u user -v -d target`

**Comment by hellojoe88** [comment]
Yes. I mapped my docker container to an external folder and copied the new script to it. Am 10.01.2023 19:36 schrieb Patrice ***@***.***>:

Did you install the updated mca-dump-short in the right spot(s)?Sent from my iPadOn Jan 10, 2023, at 9:41 AM, Johannes Pfeifer ***@***.***> wrote:﻿

Thank you so much, this is much appreciated! Especially since you have done it so fast.

I tested it and got this error:

`Preprocessing failed for: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b.Usage /usr/lib/zabbix/exte...



Result: /usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b.Usage /usr/lib/zabbix/exte...

Failed: cannot extract value from json by path "$.sys_stats.mem_total": invalid object format, expected opening character '{' or '[' at: '/usr/lib/zabbix/externalscripts/mca-dump-short.sh: illegal option -- b

Usage /usr/lib/zabbix/externalscripts/mca-dump-short.sh -i privateKeyPath -p  -u user -v -d target`

**Comment by patricegautier** [comment]
Apologies I hadn't committed the correct mac-dump script to the right spot.. Please update and let me know..

**Comment by hellojoe88** [comment]
That fixed the problem for me. Now the client count is being monitored by zabbix. Amazing! Thank you so much.
